# TODO(Phase 10 / T-004): Skeleton only. Implementation per
# docs/specs/phase10-implementation-standards.md
"""FrameworkMeta — framework-managed metadata slot for DataObject.

Implements ADR-027 D5 (stratified metadata). The ``framework`` slot on
every ``DataObject`` is an immutable Pydantic ``BaseModel`` containing
fields the framework owns and block authors do not mutate:

- ``created_at``  — when the object was first instantiated
- ``object_id``   — stable identifier (UUID-style) for lineage joins
- ``source``      — free-form origin description (e.g. file path)
- ``lineage_id``  — link into the ``LineageRecorder`` graph
- ``derived_from`` — parent object_id when this is a derived slice

Block authors read these fields but never write to them. The
``with_meta(...)`` helper on ``DataObject`` updates the ``meta`` slot
only; ``framework`` is regenerated by the framework when a derived
instance is produced (per ADR-027 D5 propagation rules).

This module is a *skeleton*. Method bodies / class bodies raise
``NotImplementedError`` where applicable; the implementation lands in
T-004.
"""

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class FrameworkMeta(BaseModel):
    """Immutable framework-managed metadata.

    See ADR-027 D5 for the field semantics. Pydantic v2 validates and
    JSON-round-trips this model automatically as part of the worker
    subprocess transport (ADR-027 Addendum 1 §1).
    """

    # TODO(T-004): ADR-027 D5 — declare the five fields with the right
    # types and defaults:
    #
    #   created_at:   datetime              # default: datetime.utcnow()
    #   object_id:    str                   # default: uuid4().hex
    #   source:       str = ""              # free-form origin description
    #   lineage_id:   str | None = None     # link into LineageRecorder
    #   derived_from: str | None = None     # parent object_id
    #
    # Use ``Field(default_factory=...)`` for ``created_at`` and
    # ``object_id`` so that every instance gets a fresh value rather
    # than a shared module-level singleton.
    #
    # Pydantic ``model_config`` should set ``frozen=True`` so that
    # accidental mutation raises ValidationError. ADR-027 Addendum 1 §3
    # also requires ``frozen=True`` on ``Meta`` subclasses; matching that
    # convention on ``FrameworkMeta`` keeps the rules consistent.
    created_at: datetime = Field(default_factory=lambda: datetime.utcnow())
    object_id: str = Field(default="")
    source: str = ""
    lineage_id: str | None = None
    derived_from: str | None = None

    # NOTE: T-004 will replace the placeholder defaults above with the
    # final implementation (uuid4-based object_id, frozen=True config,
    # validators where needed). The current defaults exist only so the
    # skeleton model is importable and instantiable for type-checking.

    def derive(self, **changes: Any) -> FrameworkMeta:
        """Return a new FrameworkMeta for a derived object.

        ADR-027 D5 propagation rule: derived slices get a fresh
        ``object_id``, ``created_at=now()``, and ``derived_from`` set to
        the parent's ``object_id``. Other fields (``source``,
        ``lineage_id``) are inherited unless overridden by ``changes``.
        """
        # TODO(T-004): ADR-027 D5 — implement derive() per the
        # propagation rule above. Used by Array.sel(), Array.iter_over(),
        # and iterate_over_axes() to keep lineage hints consistent.
        raise NotImplementedError("T-004: ADR-027 D5 — FrameworkMeta.derive() not yet implemented")
