"""FrameworkMeta — framework-managed immutable metadata slot for DataObject.

Implements ADR-027 D5 (stratified metadata).

This is the ``framework`` slot on every ``DataObject``. It is populated
by the framework at object creation time and is read-only from block
authors' perspective. The fields trace provenance, lineage, and
identity:

- ``created_at``  — when the object was first instantiated (UTC)
- ``object_id``   — stable UUIDv4 identifier for lineage joins
- ``source``      — free-form origin description (e.g. file path)
- ``lineage_id``  — link into the ``LineageRecorder`` graph
- ``derived_from`` — parent ``object_id`` when this is a derived slice

Block authors read these fields but never write to them. The
``with_meta(...)`` helper on ``DataObject`` (T-005) updates the
``meta`` slot only; ``framework`` is regenerated by the framework when
a derived instance is produced (per ADR-027 D5 propagation rules) via
:meth:`FrameworkMeta.derive`.
"""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


class FrameworkMeta(BaseModel):
    """Framework-managed metadata slot, populated at DataObject construction.

    Block authors do NOT mutate this directly. The framework writes
    these fields when constructing a new ``DataObject`` (T-005) or when
    deriving a new instance via ``iter_over`` / ``sel`` /
    ``iterate_over_axes`` (T-006, T-011).

    The model is frozen per ADR-027 D5 so accidental mutation raises a
    ``ValidationError``. Pydantic v2 validates and JSON-round-trips this
    model automatically as part of the worker subprocess transport
    (ADR-027 Addendum 1 §1).

    Attributes:
        created_at: UTC timestamp of construction.
        object_id: UUIDv4 hex string, unique per ``DataObject`` instance.
        source: Free-form origin description (e.g. file path, block
            name). Defaults to ``""`` when no specific source is known.
        lineage_id: Optional foreign key into ``LineageRecorder`` for
            the block execution that produced this object. ``None`` if
            the object was constructed outside a block run (e.g. in a
            test).
        derived_from: Optional parent ``object_id`` for objects produced
            by slicing or iterating (e.g. a slice of a 5D image carries
            the 5D image's ``object_id`` here).
    """

    model_config = ConfigDict(frozen=True)

    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    object_id: str = Field(default_factory=lambda: uuid4().hex)
    source: str = ""
    lineage_id: str | None = None
    derived_from: str | None = None

    def derive(self, **changes: Any) -> FrameworkMeta:
        """Return a new ``FrameworkMeta`` for a derived object.

        ADR-027 D5 propagation rule: derived slices get a fresh
        ``object_id``, a fresh ``created_at``, and ``derived_from`` set
        to the parent's ``object_id``. Other fields (``source``,
        ``lineage_id``) are inherited unless explicitly overridden via
        ``changes``.

        Used by ``Array.sel()``, ``Array.iter_over()``, and
        ``iterate_over_axes()`` (T-006, T-011) to keep lineage hints
        consistent across derivations.

        Args:
            **changes: Optional field overrides applied after the
                propagation defaults. Any of ``created_at``,
                ``object_id``, ``source``, ``lineage_id``, or
                ``derived_from`` may be overridden.

        Returns:
            A new ``FrameworkMeta`` instance. The original is unchanged
            (the model is frozen).

        Example:
            >>> parent = FrameworkMeta(source="raw.tif")
            >>> child = parent.derive()
            >>> child.derived_from == parent.object_id
            True
            >>> child.source == parent.source
            True
            >>> child.object_id != parent.object_id
            True
        """
        return type(self)(
            created_at=changes.pop("created_at", datetime.now(UTC)),
            object_id=changes.pop("object_id", uuid4().hex),
            source=changes.pop("source", self.source),
            lineage_id=changes.pop("lineage_id", self.lineage_id),
            derived_from=changes.pop("derived_from", self.object_id),
            **changes,
        )
